<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.phenix</groupId>
    <artifactId>adobepremiereproject</artifactId>
    <version>0.3.10</version>
    <packaging>jar</packaging>
    
    <name>AdobePremiereProject</name>
    <description>Librairie qui génère des projets Adobe Premiere Pro.</description>
    <url>https://github.com/edouard333/AdobePremiereProject</url>
    
    <developers>
        <developer>
            <name>Edouard Jeanjean</name>
            <email>edouard128@hotmail.com</email>
            <url>https://github.com/edouard333</url>
        </developer>
    </developers>
    
    <build>
        <plugins>
            <!-- Fait des vérifications sur le projet. -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <version>3.6.2</version>
                <executions>
                    <execution>
                        <id>enforce-files-exist</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <!-- Vérifie qu'on utilise la bonne version de JDK. -->
                                <requireJavaVersion>
                                    <version>25</version>
                                </requireJavaVersion>
                                <!-- Vérifie qu'est indiqué le mode d'encodage des sources. -->
                                <requireProperty>
                                    <property>project.build.sourceEncoding</property>
                                    <regex>^(UTF-8)$</regex>
                                    <message>Le sourceEncoding doit être renseigné.</message>
                                    <regexMessage>Le sourceEncoding doit être "UTF-8".</regexMessage>
                                </requireProperty>
                                <!-- Vérifie qu'est indiqué la version du JDK pour la compilation. -->
                                <requireProperty>
                                    <property>maven.compiler.release</property>
                                    <regex>^(25)$</regex>
                                    <message>La version du JDK (compiler.release) doit être 25.</message>
                                </requireProperty>
                                <!-- Vérifie que les propriétés existent et ont des valeurs valides. -->
                                <requireProperty>
                                    <property>appType</property>
                                    <message>"appType" doit être défini.</message>
                                    <regex>^(graphic|console|library)$</regex>
                                    <regexMessage>La valeur doit être soit "graphic" soit "console" soit "library".</regexMessage>
                                </requireProperty>
                            </rules>
                            <fail>true</fail>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            
            <!-- Ajoute le code source dans Maven. -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.4.0</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        
            <!-- Ajoute la JavaDoc dans Maven. -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>3.12.0</version>
                <executions>
                    <execution>
                        <id>attach-javadoc</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            
            <!-- Génère des checksums. -->
            <plugin>
                <groupId>net.nicoulaj.maven.plugins</groupId>
                <artifactId>checksum-maven-plugin</artifactId>
                <version>1.11</version>
                <executions>
                    <execution>
                        <phase>verify</phase>
                        <goals>
                            <goal>files</goal>
                        </goals>
                        <configuration>
                            <fileSets>
                                <!-- Inclure les fichiers de build Maven. -->
                                <fileSet>
                                    <directory>${project.build.directory}</directory>
                                    <includes>
                                        <include>*-${project.version}.jar</include>
                                        <include>*-${project.version}-sources.jar</include>
                                        <include>*-${project.version}-javadoc.jar</include>
                                    </includes>
                                </fileSet>
                            </fileSets>
                            <csvSummaryFile>checksums-${project.version}.csv</csvSummaryFile>
                            <!-- L'algorithme de hash. -->
                            <algorithms>
                                <algorithm>SHA-1</algorithm>
                                <algorithm>MD5</algorithm>
                            </algorithms>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    
    <dependencies>
        <dependency>
            <groupId>com.phenix</groupId>
            <artifactId>codec</artifactId>
            <version>0.3.2</version>
        </dependency>
        <dependency>
            <groupId>com.phenix</groupId>
            <artifactId>compression</artifactId>
            <version>0.3.3</version>
        </dependency>
        <dependency>
            <groupId>com.phenix</groupId>
            <artifactId>timecode</artifactId>
            <version>0.8.4</version>
        </dependency>
        <!-- Ajout des annotations @NotNull, etc. -->
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
            <version>3.1.1</version>
        </dependency>
    </dependencies>
    
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>25</maven.compiler.release>
        <!-- Type d'application : "graphic", "console" ou "library". -->
        <appType>library</appType>
    </properties>
</project>