<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.phenix</groupId>
    <artifactId>adobepremiereproject</artifactId>
    <name>AdobePremiereProject</name>
    <version>0.3.4</version>
    <packaging>jar</packaging>
    <url>https://github.com/edouard333/AdobePremiereProject</url>
    
    <developers>
        <developer>
            <name>Edouard Jeanjean</name>
            <email>edouard128@hotmail.com</email>
        </developer>
    </developers>
    
    <build>
        <plugins>
            <!-- Ajoute le code source dans Maven. -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.3.1</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        
            <!-- Ajoute la JavaDoc dans Maven. -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>3.11.2</version>
                <executions>
                    <execution>
                        <id>attach-javadoc</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    
    <dependencies>
        <dependency>
            <groupId>com.phenix</groupId>
            <artifactId>codec</artifactId>
            <version>0.3.0</version>
        </dependency>
        <dependency>
            <groupId>com.phenix</groupId>
            <artifactId>compression</artifactId>
            <version>0.3.0</version>
        </dependency>
        <dependency>
            <groupId>com.phenix</groupId>
            <artifactId>timecode</artifactId>
            <version>0.8.0</version>
        </dependency>
    </dependencies>
    
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <!-- Type d'application : "graphic", "console" ou "library". -->
        <appType>library</appType>
    </properties>
</project>